server:
  port: 8084

curator:
  #重试次数
  maxRetries: 5
  #重试间隔时间
  elapsedTimeMs: 5000
  # zookeeper 地址
  serverLists: 192.168.255.133:2181,192.168.255.134:2181,192.168.255.136:2181
  # session超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000
  # 权限管理  user:pwd
  digest:
  # 当前命名空间
  # base-namespace  discovery-namespace lock-namespace
  namespace: lock-namespace

swagger:
  enable: true

#服务发现 根节点   enable为true时开启
discovery:
  enable: false
  path: /rootNode
  serviceName: serviceDiscovery
  desc: 测试节点1
  weight: 1

#分布式锁
lock:
  enable: false
  path: /lockNode

#设置编码格式
spring:
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
